import Banner from "@/components/Banner";
import Navigation from "@/components/Navigation";
import { ProjectGallery } from "@/components/ProjectGallery";
import { getProjectsData, ProjectPost } from "@/lib/projects";
import Head from "next/head";

export async function getStaticProps() {
    const projects = await getProjectsData();
    return {
        props: {
            projects,
        },
    };
}

interface HomeProps {
    projects: ProjectPost[];
}

export default function Home({ projects }: HomeProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navigation isHomePage />
                <Banner />
                <ProjectGallery projects={projects} />
            </main>
        </>
    );
}
